"""add is_available to exchange_book

Revision ID: 1757c1f3b4b5
Revises: 47cb41854238
Create Date: 2026-02-26 21:19:52.152040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1757c1f3b4b5'
down_revision: Union[str, Sequence[str], None] = '47cb41854238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_books', sa.Column('is_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_books', 'is_available')
    # ### end Alembic commands ###
