"""added is_active to user

Revision ID: d07d4511be5c
Revises: 5665ba7d2bd4
Create Date: 2026-02-28 18:02:25.649787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd07d4511be5c'
down_revision: Union[str, Sequence[str], None] = '5665ba7d2bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
#     # ### end Alembic commands ###

def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )

    # Optional but clean practice:
    op.alter_column('users', 'is_active', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
